"""create question table

Revision ID: 6f899ea9e001
Revises: 
Create Date: 2024-08-11 01:53:47.068047

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f899ea9e001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.String(length=255), nullable=False),
    sa.Column('question_index', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(length=255), nullable=False),
    sa.Column('option1', sa.String(length=255), nullable=False),
    sa.Column('option2', sa.String(length=255), nullable=False),
    sa.Column('option3', sa.String(length=255), nullable=False),
    sa.Column('option4', sa.String(length=255), nullable=False),
    sa.Column('answer', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('question')
    # ### end Alembic commands ###
