"""Added Quiz and Question models

Revision ID: 71574847c182
Revises: 6f899ea9e001
Create Date: 2024-09-04 11:59:04.005545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71574847c182'
down_revision = '6f899ea9e001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quizzes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('image', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quiz_id', sa.Integer(), nullable=False),
    sa.Column('question_index', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(length=255), nullable=False),
    sa.Column('option1', sa.String(length=255), nullable=False),
    sa.Column('option2', sa.String(length=255), nullable=False),
    sa.Column('option3', sa.String(length=255), nullable=False),
    sa.Column('option4', sa.String(length=255), nullable=False),
    sa.Column('answer', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('question')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('question_id', sa.VARCHAR(length=255), nullable=False),
    sa.Column('question_index', sa.INTEGER(), nullable=False),
    sa.Column('question', sa.VARCHAR(length=255), nullable=False),
    sa.Column('option1', sa.VARCHAR(length=255), nullable=False),
    sa.Column('option2', sa.VARCHAR(length=255), nullable=False),
    sa.Column('option3', sa.VARCHAR(length=255), nullable=False),
    sa.Column('option4', sa.VARCHAR(length=255), nullable=False),
    sa.Column('answer', sa.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('questions')
    op.drop_table('quizzes')
    # ### end Alembic commands ###
